name: Zip and Send .bru Files to Slack

on:
  push:
    branches:
      - main

jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and zip .bru files
        run: |
          find . -name "*.bru" -print | zip api_tests.zip -@

      - name: Upload .bru files to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -F file=@api_tests.zip -F channels=#your-channel -H "Authorization: Bearer $SLACK_TOKEN" https://slack.com/api/files.upload
